### ISSUE TITLE
Cannot find module '../config

### ISSUE THREAD

**Issue by selfEVO** [xialvjun/zhihu_favorites#1]
Hi xialvjun ,I encoutered this problem after installing all the required modules.  need your help ...

Does this file has a format ? Could you please give me an example ?

```
index.ts:3:31 - error TS2307: Cannot find module '../config' or its corresponding type declarations.

3 import { crap_user_url } from '../config';
```

**Comment by xialvjun** [comment]
Now it works. See readme.

**Comment by selfEVO** [comment]
After your update and  my reinstallation of nodejs/npm, it works !  Thanks you for your excellent work !

btw, do you have plan to develope funtions like crawling the content of the article ? that would be perfect.  

Here is my nodejs version and npm version:
```
npm -v
7.16.0
node -v
v14.17.0
```
