### ISSUE TITLE
请问 行 7 字符：32 错误：语法错误 代码：800A03EA 源 Microsoft JScript编译错误 是什么问题

### ISSUE THREAD

**Issue by freemedom** [xialvjun/zhihu_favorites#2]
![image](https://user-images.githubusercontent.com/57294686/132694161-cb3dfa33-6e1f-4ad4-85d0-fda89d940089.png)

**Comment by freemedom** [comment]
我是在cmd上直接运行的

**Comment by xialvjun** [comment]
那个，我不是写了 usage 吗   https://github.com/xialvjun/zhihu_favorites#usage

**Comment by xialvjun** [comment]
使用 nodejs 去运行，而不是 windows 上直接用 JScript 去运行
